// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ExtendedVnftClientProgram;
impl sails_rs::client::Program for ExtendedVnftClientProgram {}
pub trait ExtendedVnftClient {
    type Env: sails_rs::client::GearEnv;
    fn vnft(&self) -> sails_rs::client::Service<vnft::VnftImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVnftClient
    for sails_rs::client::Actor<ExtendedVnftClientProgram, E>
{
    type Env = E;
    fn vnft(&self) -> sails_rs::client::Service<vnft::VnftImpl, Self::Env> {
        self.service(stringify!(Vnft))
    }
}
pub trait ExtendedVnftClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
    ) -> sails_rs::client::PendingCtor<ExtendedVnftClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVnftClientCtors
    for sails_rs::client::Deployment<ExtendedVnftClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
    ) -> sails_rs::client::PendingCtor<ExtendedVnftClientProgram, io::New, Self::Env> {
        self.pending_ctor((name, symbol))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String) -> ());
}

pub mod vnft {
    use super::*;
    pub trait Vnft {
        type Env: sails_rs::client::GearEnv;
        fn burn(
            &mut self,
            from: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env>;
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env>;
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env>;
        fn mint(
            &mut self,
            to: ActorId,
            token_metadata: TokenMetadata,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env>;
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env>;
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env>;
        fn approve(
            &mut self,
            approved: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env>;
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        fn token_id(&self) -> sails_rs::client::PendingCall<io::TokenId, Self::Env>;
        fn token_metadata_by_id(
            &self,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::TokenMetadataById, Self::Env>;
        fn tokens_for_owner(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::TokensForOwner, Self::Env>;
        fn balance_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn get_approved(
            &self,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::GetApproved, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn owner_of(&self, token_id: U256)
        -> sails_rs::client::PendingCall<io::OwnerOf, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
    }
    pub struct VnftImpl;
    impl<E: sails_rs::client::GearEnv> Vnft for sails_rs::client::Service<VnftImpl, E> {
        type Env = E;
        fn burn(
            &mut self,
            from: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, token_id))
        }
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env> {
            self.pending_call((to,))
        }
        fn mint(
            &mut self,
            to: ActorId,
            token_metadata: TokenMetadata,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, token_metadata))
        }
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env> {
            self.pending_call((from,))
        }
        fn approve(
            &mut self,
            approved: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((approved, token_id))
        }
        fn transfer(
            &mut self,
            to: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, token_id))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, token_id))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env> {
            self.pending_call(())
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn token_id(&self) -> sails_rs::client::PendingCall<io::TokenId, Self::Env> {
            self.pending_call(())
        }
        fn token_metadata_by_id(
            &self,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::TokenMetadataById, Self::Env> {
            self.pending_call((token_id,))
        }
        fn tokens_for_owner(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::TokensForOwner, Self::Env> {
            self.pending_call((owner,))
        }
        fn balance_of(
            &self,
            owner: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((owner,))
        }
        fn get_approved(
            &self,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::GetApproved, Self::Env> {
            self.pending_call((token_id,))
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn owner_of(
            &self,
            token_id: U256,
        ) -> sails_rs::client::PendingCall<io::OwnerOf, Self::Env> {
            self.pending_call((token_id,))
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Burn (from: ActorId, token_id: U256) -> ());
        sails_rs::io_struct_impl!(GrantAdminRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantBurnerRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantMinterRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(Mint (to: ActorId, token_metadata: super::TokenMetadata) -> ());
        sails_rs::io_struct_impl!(RevokeAdminRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeBurnerRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeMinterRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(Approve (approved: ActorId, token_id: U256) -> ());
        sails_rs::io_struct_impl!(Transfer (to: ActorId, token_id: U256) -> ());
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, token_id: U256) -> ());
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Burners () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(TokenId () -> U256);
        sails_rs::io_struct_impl!(TokenMetadataById (token_id: U256) -> Option<super::TokenMetadata>);
        sails_rs::io_struct_impl!(TokensForOwner (owner: ActorId) -> Vec<(U256,super::TokenMetadata,)>);
        sails_rs::io_struct_impl!(BalanceOf (owner: ActorId) -> U256);
        sails_rs::io_struct_impl!(GetApproved (token_id: U256) -> ActorId);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(OwnerOf (token_id: U256) -> ActorId);
        sails_rs::io_struct_impl!(Symbol () -> String);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VnftEvents {
            Minted {
                to: ActorId,
                token_metadata: TokenMetadata,
            },
            Burned {
                from: ActorId,
                token_id: U256,
            },
            Transfer {
                from: ActorId,
                to: ActorId,
                token_id: U256,
            },
            Approval {
                owner: ActorId,
                approved: ActorId,
                token_id: U256,
            },
        }
        impl sails_rs::client::Event for VnftEvents {
            const EVENT_NAMES: &'static [Route] = &["Minted", "Burned", "Transfer", "Approval"];
        }
        impl sails_rs::client::ServiceWithEvents for VnftImpl {
            type Event = VnftEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TokenMetadata {
    pub name: String,
    pub description: String,
    pub media: String,
    pub reference: String,
}
