// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ExtendedVmtClientProgram;
impl sails_rs::client::Program for ExtendedVmtClientProgram {}
pub trait ExtendedVmtClient {
    type Env: sails_rs::client::GearEnv;
    fn vmt(&self) -> sails_rs::client::Service<vmt::VmtImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVmtClient
    for sails_rs::client::Actor<ExtendedVmtClientProgram, E>
{
    type Env = E;
    fn vmt(&self) -> sails_rs::client::Service<vmt::VmtImpl, Self::Env> {
        self.service(stringify!(Vmt))
    }
}
pub trait ExtendedVmtClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
    ) -> sails_rs::client::PendingCtor<ExtendedVmtClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVmtClientCtors
    for sails_rs::client::Deployment<ExtendedVmtClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
    ) -> sails_rs::client::PendingCtor<ExtendedVmtClientProgram, io::New, Self::Env> {
        self.pending_ctor((name, symbol, decimals))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String, decimals: u8) -> ());
}

pub mod vmt {
    use super::*;
    pub trait Vmt {
        type Env: sails_rs::client::GearEnv;
        fn burn(
            &mut self,
            from: ActorId,
            id: U256,
            amount: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        fn burn_batch(
            &mut self,
            from: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BurnBatch, Self::Env>;
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env>;
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env>;
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env>;
        fn mint(
            &mut self,
            to: ActorId,
            id: U256,
            amount: U256,
            token_metadata: Option<TokenMetadata>,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        fn mint_batch(
            &mut self,
            to: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
            token_metadata: Vec<Option<TokenMetadata>>,
        ) -> sails_rs::client::PendingCall<io::MintBatch, Self::Env>;
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env>;
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env>;
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env>;
        /// Approves an `ActorId` (account) to transfer tokens on behalf of the owner (sender).
        /// If the approval is successful, it emits an `Approval` event.
        fn approve(&mut self, to: ActorId)
        -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        /// Transfers multiple tokens in batch from one account (`from`) to another (`to`).
        /// This method transfers multiple token IDs and amounts simultaneously.
        fn batch_transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BatchTransferFrom, Self::Env>;
        /// Transfers tokens from one account (`from`) to another (`to`) if the sender is allowed.
        /// Emits a `Transfer` event after a successful transfer.
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            id: U256,
            amount: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env>;
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        /// Returns the token balance of an account (`account`) for a specific token ID (`id`).
        fn balance_of(
            &self,
            account: ActorId,
            id: U256,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        /// Returns token account balances (`accounts`) for specific token identifiers (`ids`).
        fn balance_of_batch(
            &self,
            accounts: Vec<ActorId>,
            ids: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BalanceOfBatch, Self::Env>;
        /// Returns the number of decimal places used for this token.
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        /// Checks if a specific operator (`operator`) is approved to transfer tokens on behalf of `account`.
        /// Returns true if the operator is approved.
        fn is_approved(
            &self,
            account: ActorId,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApproved, Self::Env>;
        /// Returns the name of the token.
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        /// Returns the symbol of the token.
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        /// Returns the total supply of tokens in circulation.
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
    }
    pub struct VmtImpl;
    impl<E: sails_rs::client::GearEnv> Vmt for sails_rs::client::Service<VmtImpl, E> {
        type Env = E;
        fn burn(
            &mut self,
            from: ActorId,
            id: U256,
            amount: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, id, amount))
        }
        fn burn_batch(
            &mut self,
            from: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BurnBatch, Self::Env> {
            self.pending_call((from, ids, amounts))
        }
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env> {
            self.pending_call((to,))
        }
        fn mint(
            &mut self,
            to: ActorId,
            id: U256,
            amount: U256,
            token_metadata: Option<TokenMetadata>,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, id, amount, token_metadata))
        }
        fn mint_batch(
            &mut self,
            to: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
            token_metadata: Vec<Option<TokenMetadata>>,
        ) -> sails_rs::client::PendingCall<io::MintBatch, Self::Env> {
            self.pending_call((to, ids, amounts, token_metadata))
        }
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env> {
            self.pending_call((from,))
        }
        fn approve(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((to,))
        }
        fn batch_transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            ids: Vec<U256>,
            amounts: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BatchTransferFrom, Self::Env> {
            self.pending_call((from, to, ids, amounts))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            id: U256,
            amount: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, id, amount))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env> {
            self.pending_call(())
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn balance_of(
            &self,
            account: ActorId,
            id: U256,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account, id))
        }
        fn balance_of_batch(
            &self,
            accounts: Vec<ActorId>,
            ids: Vec<U256>,
        ) -> sails_rs::client::PendingCall<io::BalanceOfBatch, Self::Env> {
            self.pending_call((accounts, ids))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn is_approved(
            &self,
            account: ActorId,
            operator: ActorId,
        ) -> sails_rs::client::PendingCall<io::IsApproved, Self::Env> {
            self.pending_call((account, operator))
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Burn (from: ActorId, id: U256, amount: U256) -> ());
        sails_rs::io_struct_impl!(BurnBatch (from: ActorId, ids: Vec<U256>, amounts: Vec<U256>) -> ());
        sails_rs::io_struct_impl!(GrantAdminRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantBurnerRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantMinterRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(Mint (to: ActorId, id: U256, amount: U256, token_metadata: Option<super::TokenMetadata>) -> ());
        sails_rs::io_struct_impl!(MintBatch (to: ActorId, ids: Vec<U256>, amounts: Vec<U256>, token_metadata: Vec<Option<super::TokenMetadata>>) -> ());
        sails_rs::io_struct_impl!(RevokeAdminRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeBurnerRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeMinterRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(Approve (to: ActorId) -> bool);
        sails_rs::io_struct_impl!(BatchTransferFrom (from: ActorId, to: ActorId, ids: Vec<U256>, amounts: Vec<U256>) -> ());
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, id: U256, amount: U256) -> ());
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Burners () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId, id: U256) -> U256);
        sails_rs::io_struct_impl!(BalanceOfBatch (accounts: Vec<ActorId>, ids: Vec<U256>) -> Vec<U256>);
        sails_rs::io_struct_impl!(Decimals () -> u8);
        sails_rs::io_struct_impl!(IsApproved (account: ActorId, operator: ActorId) -> bool);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(Symbol () -> String);
        sails_rs::io_struct_impl!(TotalSupply () -> Vec<(U256,U256,)>);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VmtEvents {
            Minted {
                to: ActorId,
                ids: Vec<U256>,
                amounts: Vec<U256>,
            },
            Burned {
                from: ActorId,
                ids: Vec<U256>,
                amounts: Vec<U256>,
            },
            Approval {
                from: ActorId,
                to: ActorId,
            },
            Transfer {
                from: ActorId,
                to: ActorId,
                ids: Vec<U256>,
                amounts: Vec<U256>,
            },
        }
        impl sails_rs::client::Event for VmtEvents {
            const EVENT_NAMES: &'static [Route] = &["Minted", "Burned", "Approval", "Transfer"];
        }
        impl sails_rs::client::ServiceWithEvents for VmtImpl {
            type Event = VmtEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct TokenMetadata {
    pub title: Option<String>,
    pub description: Option<String>,
    pub media: Option<String>,
    pub reference: Option<String>,
}
