// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ExtendedVftClientProgram;
impl sails_rs::client::Program for ExtendedVftClientProgram {}
pub trait ExtendedVftClient {
    type Env: sails_rs::client::GearEnv;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVftClient
    for sails_rs::client::Actor<ExtendedVftClientProgram, E>
{
    type Env = E;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env> {
        self.service(stringify!(Vft))
    }
}
pub trait ExtendedVftClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
    ) -> sails_rs::client::PendingCtor<ExtendedVftClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVftClientCtors
    for sails_rs::client::Deployment<ExtendedVftClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
    ) -> sails_rs::client::PendingCtor<ExtendedVftClientProgram, io::New, Self::Env> {
        self.pending_ctor((name, symbol, decimals))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String, decimals: u8) -> ());
}

pub mod vft {
    use super::*;
    pub trait Vft {
        type Env: sails_rs::client::GearEnv;
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env>;
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env>;
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env>;
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env>;
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env>;
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env>;
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env>;
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
    }
    pub struct VftImpl;
    impl<E: sails_rs::client::GearEnv> Vft for sails_rs::client::Service<VftImpl, E> {
        type Env = E;
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, value))
        }
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env> {
            self.pending_call((to,))
        }
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, value))
        }
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env> {
            self.pending_call((from,))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env> {
            self.pending_call(())
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Burn (from: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(GrantAdminRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantBurnerRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantMinterRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(Mint (to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(RevokeAdminRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeBurnerRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeMinterRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Burners () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256);
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256);
        sails_rs::io_struct_impl!(Decimals () -> u8);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(Symbol () -> String);
        sails_rs::io_struct_impl!(TotalSupply () -> U256);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VftEvents {
            Minted {
                to: ActorId,
                value: U256,
            },
            Burned {
                from: ActorId,
                value: U256,
            },
            Approval {
                owner: ActorId,
                spender: ActorId,
                value: U256,
            },
            Transfer {
                from: ActorId,
                to: ActorId,
                value: U256,
            },
        }
        impl sails_rs::client::Event for VftEvents {
            const EVENT_NAMES: &'static [Route] = &["Minted", "Burned", "Approval", "Transfer"];
        }
        impl sails_rs::client::ServiceWithEvents for VftImpl {
            type Event = VftEvents;
        }
    }
}
