// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct ExtendedVftClientProgram;
impl sails_rs::client::Program for ExtendedVftClientProgram {}
pub trait ExtendedVftClient {
    type Env: sails_rs::client::GearEnv;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVftClient
    for sails_rs::client::Actor<ExtendedVftClientProgram, E>
{
    type Env = E;
    fn vft(&self) -> sails_rs::client::Service<vft::VftImpl, Self::Env> {
        self.service(stringify!(Vft))
    }
}
pub trait ExtendedVftClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        balances_caps: Option<Vec<u32>>,
        allowances_caps: Option<Vec<u32>>,
    ) -> sails_rs::client::PendingCtor<ExtendedVftClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> ExtendedVftClientCtors
    for sails_rs::client::Deployment<ExtendedVftClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        name: String,
        symbol: String,
        decimals: u8,
        balances_caps: Option<Vec<u32>>,
        allowances_caps: Option<Vec<u32>>,
    ) -> sails_rs::client::PendingCtor<ExtendedVftClientProgram, io::New, Self::Env> {
        self.pending_ctor((name, symbol, decimals, balances_caps, allowances_caps))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (name: String, symbol: String, decimals: u8, balances_caps: Option<Vec<u32>>, allowances_caps: Option<Vec<u32>>) -> ());
}

pub mod vft {
    use super::*;
    pub trait Vft {
        type Env: sails_rs::client::GearEnv;
        /// Explicitly grow allowances map
        fn alloc_next_allowances_shard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::AllocNextAllowancesShard, Self::Env>;
        /// Explicitly grow balances map
        fn alloc_next_balances_shard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::AllocNextBalancesShard, Self::Env>;
        /// Append a new shard to allowances with the given capacity
        fn append_allowances_shard(
            &mut self,
            cap: u32,
        ) -> sails_rs::client::PendingCall<io::AppendAllowancesShard, Self::Env>;
        /// Append a new shard to balances with the given capacity
        fn append_balances_shard(
            &mut self,
            cap: u32,
        ) -> sails_rs::client::PendingCall<io::AppendBalancesShard, Self::Env>;
        /// Burn tokens
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env>;
        /// Grant admin role
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env>;
        /// Grant burner role
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env>;
        /// Grant minter role
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env>;
        /// Mint new tokens
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env>;
        /// Revoke admin role
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env>;
        /// Revoke burner role
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env>;
        /// Revoke minter role
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env>;
        /// Sets allowance for `spender` from msg::source() (owner)
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env>;
        /// Transfers `value` from msg::source() to `to`
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env>;
        /// Transfers `value` from `from` to `to` on behalf of msg::source() (spender)
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env>;
        /// Returns current admins list (unordered)
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env>;
        /// Returns current burners list (unordered)
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env>;
        /// Returns current minters list (unordered)
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env>;
        /// Returns current allowance
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env>;
        /// Allowances map stats: (len, allocated_capacity, max_capacity, free_space)
        fn allowances_stats(&self)
        -> sails_rs::client::PendingCall<io::AllowancesStats, Self::Env>;
        /// Returns current balance
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env>;
        /// Balances map stats: (len, allocated_capacity, max_capacity, free_space)
        fn balances_stats(&self) -> sails_rs::client::PendingCall<io::BalancesStats, Self::Env>;
        /// Token decimals
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env>;
        /// Token name
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env>;
        /// Token symbol
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env>;
        /// Total supply
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env>;
    }
    pub struct VftImpl;
    impl<E: sails_rs::client::GearEnv> Vft for sails_rs::client::Service<VftImpl, E> {
        type Env = E;
        fn alloc_next_allowances_shard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::AllocNextAllowancesShard, Self::Env> {
            self.pending_call(())
        }
        fn alloc_next_balances_shard(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::AllocNextBalancesShard, Self::Env> {
            self.pending_call(())
        }
        fn append_allowances_shard(
            &mut self,
            cap: u32,
        ) -> sails_rs::client::PendingCall<io::AppendAllowancesShard, Self::Env> {
            self.pending_call((cap,))
        }
        fn append_balances_shard(
            &mut self,
            cap: u32,
        ) -> sails_rs::client::PendingCall<io::AppendBalancesShard, Self::Env> {
            self.pending_call((cap,))
        }
        fn burn(
            &mut self,
            from: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Burn, Self::Env> {
            self.pending_call((from, value))
        }
        fn grant_admin_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantAdminRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_burner_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantBurnerRole, Self::Env> {
            self.pending_call((to,))
        }
        fn grant_minter_role(
            &mut self,
            to: ActorId,
        ) -> sails_rs::client::PendingCall<io::GrantMinterRole, Self::Env> {
            self.pending_call((to,))
        }
        fn mint(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Mint, Self::Env> {
            self.pending_call((to, value))
        }
        fn revoke_admin_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeAdminRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_burner_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeBurnerRole, Self::Env> {
            self.pending_call((from,))
        }
        fn revoke_minter_role(
            &mut self,
            from: ActorId,
        ) -> sails_rs::client::PendingCall<io::RevokeMinterRole, Self::Env> {
            self.pending_call((from,))
        }
        fn approve(
            &mut self,
            spender: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Approve, Self::Env> {
            self.pending_call((spender, value))
        }
        fn transfer(
            &mut self,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::Transfer, Self::Env> {
            self.pending_call((to, value))
        }
        fn transfer_from(
            &mut self,
            from: ActorId,
            to: ActorId,
            value: U256,
        ) -> sails_rs::client::PendingCall<io::TransferFrom, Self::Env> {
            self.pending_call((from, to, value))
        }
        fn admins(&self) -> sails_rs::client::PendingCall<io::Admins, Self::Env> {
            self.pending_call(())
        }
        fn burners(&self) -> sails_rs::client::PendingCall<io::Burners, Self::Env> {
            self.pending_call(())
        }
        fn minters(&self) -> sails_rs::client::PendingCall<io::Minters, Self::Env> {
            self.pending_call(())
        }
        fn allowance(
            &self,
            owner: ActorId,
            spender: ActorId,
        ) -> sails_rs::client::PendingCall<io::Allowance, Self::Env> {
            self.pending_call((owner, spender))
        }
        fn allowances_stats(
            &self,
        ) -> sails_rs::client::PendingCall<io::AllowancesStats, Self::Env> {
            self.pending_call(())
        }
        fn balance_of(
            &self,
            account: ActorId,
        ) -> sails_rs::client::PendingCall<io::BalanceOf, Self::Env> {
            self.pending_call((account,))
        }
        fn balances_stats(&self) -> sails_rs::client::PendingCall<io::BalancesStats, Self::Env> {
            self.pending_call(())
        }
        fn decimals(&self) -> sails_rs::client::PendingCall<io::Decimals, Self::Env> {
            self.pending_call(())
        }
        fn name(&self) -> sails_rs::client::PendingCall<io::Name, Self::Env> {
            self.pending_call(())
        }
        fn symbol(&self) -> sails_rs::client::PendingCall<io::Symbol, Self::Env> {
            self.pending_call(())
        }
        fn total_supply(&self) -> sails_rs::client::PendingCall<io::TotalSupply, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(AllocNextAllowancesShard () -> bool);
        sails_rs::io_struct_impl!(AllocNextBalancesShard () -> bool);
        sails_rs::io_struct_impl!(AppendAllowancesShard (cap: u32) -> ());
        sails_rs::io_struct_impl!(AppendBalancesShard (cap: u32) -> ());
        sails_rs::io_struct_impl!(Burn (from: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(GrantAdminRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantBurnerRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(GrantMinterRole (to: ActorId) -> ());
        sails_rs::io_struct_impl!(Mint (to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(RevokeAdminRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeBurnerRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(RevokeMinterRole (from: ActorId) -> ());
        sails_rs::io_struct_impl!(Approve (spender: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Transfer (to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(TransferFrom (from: ActorId, to: ActorId, value: U256) -> bool);
        sails_rs::io_struct_impl!(Admins () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Burners () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Minters () -> Vec<ActorId>);
        sails_rs::io_struct_impl!(Allowance (owner: ActorId, spender: ActorId) -> U256);
        sails_rs::io_struct_impl!(AllowancesStats () -> (u128,u128,u128,u128,));
        sails_rs::io_struct_impl!(BalanceOf (account: ActorId) -> U256);
        sails_rs::io_struct_impl!(BalancesStats () -> (u128,u128,u128,u128,));
        sails_rs::io_struct_impl!(Decimals () -> u8);
        sails_rs::io_struct_impl!(Name () -> String);
        sails_rs::io_struct_impl!(Symbol () -> String);
        sails_rs::io_struct_impl!(TotalSupply () -> U256);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum VftEvents {
            Minted {
                to: ActorId,
                value: U256,
            },
            Burned {
                from: ActorId,
                value: U256,
            },
            Approval {
                owner: ActorId,
                spender: ActorId,
                value: U256,
            },
            Transfer {
                from: ActorId,
                to: ActorId,
                value: U256,
            },
        }
        impl sails_rs::client::Event for VftEvents {
            const EVENT_NAMES: &'static [Route] = &["Minted", "Burned", "Approval", "Transfer"];
        }
        impl sails_rs::client::ServiceWithEvents for VftImpl {
            type Event = VftEvents;
        }
    }
}
