[package]
name = "extended-vft"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
extended-vft-app = { path = "app" }

[build-dependencies]
extended-vft-app = { path = "app", default-features = false }
sails-rs = { workspace = true, features = ["build"] }

[dev-dependencies]
extended-vft = { path = ".", features = ["wasm-binary"] }
extended-vft-client = { path = "client" }
sails-rs = { workspace = true, features = ["gtest"] }
tokio.workspace = true
gclient.workspace = true
gear-core.workspace = true
gear-utils.workspace = true

[features]
wasm-binary = []
default = []
stress-tests = ["extended-vft-app/stress-tests"]
