[workspace]
resolver = "2"

members = [
    "app", "wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[workspace.dependencies]
gstd = { git = "https://github.com/gear-tech/gear", tag = "v1.5.0" }
gtest = { git = "https://github.com/gear-tech/gear", tag = "v1.5.0" }
gclient = { git = "https://github.com/gear-tech/gear", tag = "v1.5.0" }
gear-core = { git = "https://github.com/gear-tech/gear", tag = "v1.5.0" }
gwasm-builder = { git = "https://github.com/gear-tech/gear", package = "gear-wasm-builder", tag = "v1.5.0" }
parity-scale-codec = { version = "3.6", default-features = false }
sails-idl-gen = { git = "https://github.com/gear-tech/sails.git", branch = "gstd-pinned-v1.5.0" }
sails-client-gen = { git = "https://github.com/gear-tech/sails.git", branch = "gstd-pinned-v1.5.0" }
sails-rs = { git = "https://github.com/gear-tech/sails.git", branch = "gstd-pinned-v1.5.0" }
scale-info = { version = "2.10", default-features = false }
primitive-types = { version = "*", default-features = false }
derive-more = { version = "*", default-features = false, features = ["display"] }
log = "*"
env_logger = "*"
serde = "1.0"
serde-json = { package = "serde_json", version = "1.0" }
syn = "2.0"
thiserror = "1.0"
tokio = "1.36"
trybuild = "1"
vft-service = { path = "../vft-service" }
