[package]
name = "extended-vmt"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
extended-vmt-app = { path = "app" }

[build-dependencies]
extended-vmt-app = { path = "app" }
sails-rs = { workspace = true, features = ["build"] }

[features]
wasm-binary = []
